
name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip pyinstaller selenium
      - run: pyinstaller --onefile --noconsole LiteSurveyInterceptorOBF.py
      - uses: actions/upload-artifact@v4
        with:
          name: SurveyInterceptor-exe
          path: dist/LiteSurveyInterceptorOBF.exe
